#!/bin/bash

SPEC_DIR="spec/xbar"

export BUNDLE_GEMFILE=/Volumes/Opt/projects/xbar/gemfiles/rails32.gemfile

SPEC=$1
LINE=$2

if [ -n "$SPEC"  ]
then
    if [ "$SPEC" = "all" ]
    then
	TEST="all"
    else
      TEST="$SPEC_DIR/${SPEC}_spec.rb"
    fi
else
  echo "run.sh spec [line] | all"
  exit 1
fi

if [ -n "$LINE" ]
then
  TEST="${TEST}:${LINE}"
fi

if [ "$SPEC" == "all" ]
then
    bundle exec ruby -S rspec -fd -b -c ./spec/xbar/*_spec.rb
else
    bundle exec ruby -S rspec -fd -b -c ${TEST}
fi


